### ISSUE TITLE
backend / Pythonを置くインフラの選定

### ISSUE THREAD

**Issue by asha-ndf** [jphacks/KB_2302#1]

**Comment by shinnosuke1023** [comment]
## データベース
- テーブルデータ
    - NoSQL
       - firebase(firestore database)
         検索の仕様によってはたぶんめんどい（elasticsearchが要る）
- 画像データ
  - firebase(storage)

## バックエンド
DB中継(特に検索)くらい？
- 開発言語
  - Python
- デプロイ先
  - Heroku Basic
    - スリープへの移行なし
    - 無料SSL

## 今後
- 画像
- 動画？
